// <auto-generated />
using System;
using ColdVerdge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ColdVerdge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColdVerdge.Domain.Entities.InventoryGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_after");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "RequestId")
                        .IsUnique();

                    b.ToTable("inventory_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_grants_quantity_after_positive", "quantity_after > 0");

                            t.HasCheckConstraint("ck_inventory_grants_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.PlayerInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_id");

                    b.Property<string>("EquipmentSlot")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("equipment_slot");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique();

                    b.HasIndex("PlayerId", "EquipmentSlot")
                        .IsUnique()
                        .HasFilter("equipment_slot IS NOT NULL");

                    b.ToTable("player_inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_inventory_items_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.PlayerProgress", b =>
                {
                    b.Property<Guid>("PlayerId").HasColumnType("uuid").HasColumnName("player_id");
                    b.Property<int>("Agility").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(10).HasColumnName("agility");
                    b.Property<int>("AssaultRifles").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("assault_rifles");
                    b.Property<int>("CurrentExperience").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("current_experience");
                    b.Property<int>("Endurance").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(10).HasColumnName("endurance");
                    b.Property<int>("FreeAttributePoints").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("free_attribute_points");
                    b.Property<int>("Intelligence").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(10).HasColumnName("intelligence");
                    b.Property<int>("Level").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(1).HasColumnName("level");
                    b.Property<int>("MachineGuns").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("machine_guns");
                    b.Property<int>("Medicine").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("medicine");
                    b.Property<int>("Perception").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(10).HasColumnName("perception");
                    b.Property<int>("Pistols").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("pistols");
                    b.Property<int>("ProfessionExperience").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("profession_experience");
                    b.Property<string>("ProfessionId").IsRequired().ValueGeneratedOnAdd().HasMaxLength(64).HasColumnType("character varying(64)").HasDefaultValue("").HasColumnName("profession_id");
                    b.Property<int>("Shotguns").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("shotguns");
                    b.Property<int>("SniperRifles").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("sniper_rifles");
                    b.Property<int>("Strength").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(10).HasColumnName("strength");
                    b.Property<int>("SubmachineGuns").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("submachine_guns");
                    b.Property<int>("Throwables").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("throwables");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone").HasColumnName("updated_at_utc");

                    b.HasKey("PlayerId");
                    b.ToTable("player_progress", (string)null);
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.PlayerWallet", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long>("Copper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("copper");

                    b.Property<long>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("gold");

                    b.HasKey("PlayerId");

                    b.ToTable("player_wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_wallets_copper_non_negative", "copper >= 0");

                            t.HasCheckConstraint("ck_player_wallets_gold_non_negative", "gold >= 0");
                        });
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.PlayerProgress", b =>
                {
                    b.HasOne("ColdVerdge.Domain.Entities.Player", "Player")
                        .WithOne("Progress")
                        .HasForeignKey("ColdVerdge.Domain.Entities.PlayerProgress", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "RequestId")
                        .IsUnique();

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.InventoryGrant", b =>
                {
                    b.HasOne("ColdVerdge.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.PlayerInventoryItem", b =>
                {
                    b.HasOne("ColdVerdge.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.PlayerWallet", b =>
                {
                    b.HasOne("ColdVerdge.Domain.Entities.Player", "Player")
                        .WithOne("Wallet")
                        .HasForeignKey("ColdVerdge.Domain.Entities.PlayerWallet", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("ColdVerdge.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ColdVerdge.Domain.Entities.Player", b =>
                {
                    b.Navigation("Progress")
                        .IsRequired();

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
